{% set name = "gli" %}
{% set version = "2.19.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 7b4305602d4c2cb02dd5e54a67eae81cd7adc5b940f9a0e4b03a02417745a960

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: |
    Build command-suite CLI apps that are awesome.
    Bootstrap your app, add commands, options and documentation while
    maintaining a well-tested idiomatic command-line app

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/davetron5000/{{ name }}

extra:
  recipe-maintainers:
    - conda-forge/ruby
    - pierrsc
