travis:
  secure:
    BINSTAR_TOKEN: Ocr1fA4ua70+p97SDVp8OPi+k7dAX5qqkTlHcnqvxjhC9c4pY0zqnEnqBDDocWNuOCyQ21X6XJ0eQg1wXE+Z+MO6lGuW2mWzAI4pmP+Oe5ceTGiSDpKnu8lqCKKUJheqO7xutC0168sR27yQm4ihRQ72d9FO5xGqoWCjc7BKAOwmjBaXib30JjikS1OAHt69JjP/WFDjcOOFkHQwYiJOpAELi4/+giAL3YY6oADyVJUKjI4+udNR3m5977HLCc/EWzRqdaHrCuueeTUsc9YWB7hVEn8VpdNbd7iA+OkfgJ77InBG10OWA8VbveLrIq4jFK49LJ6VpnIbT6/sBatFuNXoPb/Kgv2OxL7kkFs3dD/ECPqBqSUqw1n62lu2epGKxjRd1VqYZweDezV5RPwMRR4R9Vjry5L4z3naHif2iDQrxdEOluGn2nhV61LtFHXO8pb/uWmV/tQeGoWghAQ1y+kT9m4ejs81vJ8YwCBihsj8ZpAlNsDRjOTSGXiazwCkNS7vkqiHTyuir7JxXgIZ4tVJuZ7p5Bfc+YFiCVKXhaDxk2ASehiIwYyhDrDV4zgE0pq2vmBSKxoKEN9TXETcoZStOltlsigHqbVC7Vk34jjW1BkM48WzTIuV3vbar1thd/JIhfF4FuDRSEytOmNtnFwGfqB9oC84OfKVf57fOd0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
