travis:
  secure:
    BINSTAR_TOKEN: 7lCw0fvCkmhzh3P5I7cqKK0HPiGRgQXXEapxQyPAzG0myOcqI58qw2b4LQT4aoSxwQK1QQTV672jNV1vlmMd8oBGCqjwOHoEvDcIWKOnLwfGzUGHqBWozipKZPkbA3DN2ZH9JpEWVJCGVanjzgofQV/pXcndhr9OOWe8ldphjn58yTe1d3oeGtzvcleS1PRmESRkR2KbPcMR8h1l81cCbq6x6WCrQTE1d1xj/ByRfG99rRCzFf+bhRpxJLekBCnKNnnIE96XPuaSF2tg4l58Ilu54+RTTTNv9WBF6XUaJ9RpMDw2tnugGZQjtYU3gXKbVgdnF5KB0sBbuCOJJTg5GugU0oMoYuNYvIRpZtGpEiS+k0BAC6FNkiT8/thmhxrRgOpFTc68tcA2gs85vVCA1qGyAFUalEPu+sI+RAbJNiEaZhp7YBSUzU63TECuSZQkcLgH7PKs6wGADr1mmnym1gscdvujE6GYTbNnXbmCucW78XUSXgdyS2zutDNKlbD1qU9nZaskfRk35NN2KgR1sKsQ1PcHXVPLdWRdbeWZIp7cmKeCiPKIvz/mByDYLecVW0rZMzKfvtsoq50IkYeM+FnjRgPnWPPCBO+NKCuFdWmp/T7cMpVTkDldPorwuQz10UBRvoELDITzKiS54tnAm6DX7G/Zi2S2vQ7Abpyzaik=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
